### ISSUE TITLE
Regression tests required for latest lsp4mp4ij code merge

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#605] opened 2024-01-02 22:49 UTC
The latest code for lsp4ij, lsp4mp4ij and lsp4mp has been pulled in and we need to test.

Related to https://github.com/OpenLiberty/liberty-tools-intellij/issues/592

- [x] audit the automated tests to see if disabled tests can be enabled ( https://github.com/OpenLiberty/liberty-tools-intellij/issues/642 )
- [x] get automated tests passing (@turkeylurkey )
- [x] are the current automated tests sufficient?
- [x] interaction of our code with lsp4ij that is NOT tested by unit tests
- [x] how much of each feature (diagnostics, completion, quick fixes, etc) need to be tested to be confident
- [x] create test plan for lsp4ij release

**Comment by mrglavas** [comment] 2024-03-05 19:26
From the audit of the current automated tests and the known complexity of the upgrade to the more recent version of LSP4iJ, we determined that the regression testing that we do in our automated builds is not sufficient for verifying the release. Since my initial assessment we have enabled automated tests for MicroProfile completion (https://github.com/OpenLiberty/liberty-tools-intellij/issues/654) and automated tests for all language server quick fixes (https://github.com/OpenLiberty/liberty-tools-intellij/issues/653), but there's still more that we'll need to manually verify.

Paul has assembled a manual test plan which covers the language server features across MicroProfile, Jakarta EE and Liberty. I've added some additional instructions to ensure that we're verifying that specific intermittent problems that were recently addressed are indeed resolved in the release candidate build and stay resolved going forward. Before releasing this we should do a final pass over the resolved tasks in the epic here: https://github.com/OpenLiberty/liberty-tools-intellij/issues/592 and verify that those issues are still resolved in the build.

**Closed** 2024-03-21 20:41 UTC
Labels: language client, high priority, 8, lsp4ij
