### ISSUE TITLE
lsp4jakarta test GeneratedAnnotationTest failed on windows GHA run

### ISSUE THREAD

**Issue by ajm01** [OpenLiberty/liberty-tools-intellij#473] opened 2023-07-03 14:22 UTC
Run is found here: https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/5427222930/jobs/9870245100?pr=426

GeneratedAnnotationTest > GeneratedAnnotation FAILED
    java.lang.AssertionError: Listeners leaked for interface com.intellij.openapi.editor.event.DocumentListener:
    [com.intellij.openapi.vcs.impl.LineStatusTrackerManager$MyDocumentListener@5826c8d4]
        at org.junit.Assert.fail(Assert.java:89)
        at com.intellij.testFramework.EditorListenerTracker.checkListenersLeak(EditorListenerTracker.java:56)
        at com.intellij.testFramework.fixtures.impl.HeavyIdeaTestFixtureImpl.lambda$tearDown$7(HeavyIdeaTestFixtureImpl.java:158)
        at com.intellij.testFramework.RunAll$Companion$actionSequence$1$1.invoke(RunAll.kt:70)
        at com.intellij.testFramework.RunAll$Companion$actionSequence$1$1.invoke(RunAll.kt:70)
        at com.intellij.testFramework.common.RunAllKt.runAllCatching(runAll.kt:61)
        at com.intellij.testFramework.common.RunAllKt.runAll(runAll.kt:32)
        at com.intellij.testFramework.RunAll.run(RunAll.kt:21)
        at com.intellij.testFramework.fixtures.impl.HeavyIdeaTestFixtureImpl.tearDown(HeavyIdeaTestFixtureImpl.java:175)
        at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.lambda$tearDown$43(CodeInsightTestFixtureImpl.java:1416)
        at com.intellij.testFramework.EdtTestUtil.runInEdtAndWait(EdtTestUtil.java:33)
        at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.lambda$tearDown$44(CodeInsightTestFixtureImpl.java:1416)
        at com.intellij.testFramework.RunAll$Companion$actionSequence$1$1.invoke(RunAll.kt:70)
        at com.intellij.testFramework.RunAll$Companion$actionSequence$1$1.invoke(RunAll.kt:70)
        at com.intellij.testFramework.common.RunAllKt.runAllCatching(runAll.kt:61)
        at com.intellij.testFramework.common.RunAllKt.runAll(runAll.kt:32)
        at com.intellij.testFramework.RunAll$Companion.runAll(RunAll.kt:43)
        at com.intellij.testFramework.RunAll.runAll(RunAll.kt)
        at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.tearDown(CodeInsightTestFixtureImpl.java:1373)
        at com.intellij.maven.testFramework.MavenTestCase.tearDownFixtures(MavenTestCase.java:297)
        at com.intellij.maven.testFramework.MavenTestCase.lambda$tearDown$16(MavenTestCase.java:204)
        at com.intellij.testFramework.EdtTestUtil.runInEdtAndWait(EdtTestUtil.java:33)
        at com.intellij.maven.testFramework.MavenTestCase.lambda$tearDown$17(MavenTestCase.java:204)
        at com.intellij.testFramework.RunAll$Companion$actionSequence$1$1.invoke(RunAll.kt:70)
        at com.intellij.testFramework.RunAll$Companion$actionSequence$1$1.invoke(RunAll.kt:70)
        at com.intellij.testFramework.common.RunAllKt.runAllCatching(runAll.kt:61)
        at com.intellij.testFramework.common.RunAllKt.runAll(runAll.kt:32)
        at com.intellij.testFramework.RunAll.run(RunAll.kt:21)
        at com.intellij.maven.testFramework.MavenTestCase.tearDown(MavenTestCase.java:212)
        at com.intellij.maven.testFramework.MavenImportingTestCase.lambda$tearDown$6(MavenImportingTestCase.java:122)
        at com.intellij.testFramework.RunAll$Companion$actionSequence$1$1.invoke(RunAll.kt:70)
        at com.intellij.testFramework.RunAll$Companion$actionSequence$1$1.invoke(RunAll.kt:70)
        at com.intellij.testFramework.common.RunAllKt.runAllCatching(runAll.kt:61)
        at com.intellij.testFramework.common.RunAllKt.runAll(runAll.kt:32)
        at com.intellij.testFramework.RunAll$Companion.runAll(RunAll.kt:43)
        at com.intellij.testFramework.RunAll.runAll(RunAll.kt)
        at com.intellij.maven.testFramework.MavenImportingTestCase.tearDown(MavenImportingTestCase.java:113)
        at com.intellij.testFramework.UsefulTestCase.invokeTearDown(UsefulTestCase.java:431)
        at com.intellij.testFramework.UsefulTestCase.defaultRunBare(UsefulTestCase.java:419)
        at com.intellij.testFramework.UsefulTestCase.lambda$runBare$12(UsefulTestCase.java:485)
        at com.intellij.testFramework.EdtTestUtil.lambda$runInEdtAndWait$1(EdtTestUtil.java:40)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:302)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by turkeylurkey** [comment] 2024-10-30 19:07
Duplicate of #541

**Closed by turkeylurkey** 2024-10-30 19:07 UTC
Labels: bug, automated tests
