### ISSUE TITLE
Latest IntelliJ plugin not compatible with latest IntelliJ

### ISSUE THREAD

**Issue by ljgp** [OpenLiberty/liberty-tools-intellij#602] opened 2023-12-21 10:03 UTC
In the latest IntelliJ I get:
Plugin 'Liberty Tools' (version '23.0.12') is not compatible with the current version of the IDE, because it requires build 232.* or older but the current build is IU-233.11799.241

**Comment by TrevCraw** [comment] 2024-01-04 21:42
@ljgp thank you for opening an issue. We are currently working on support for IntelliJ IDEA 2023.3.x. The issue for that is here: https://github.com/OpenLiberty/liberty-tools-intellij/issues/590

**Comment by TrevCraw** [comment] 2024-01-04 21:43
Closing as duplicate of #590

**Closed by TrevCraw** 2024-01-04 21:43 UTC
Labels: duplicate
