### ISSUE TITLE
LS Integration: Slight delay when starting language servers

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-tools-intellij#88] opened 2022-09-06 18:41 UTC
When you open a microprofile-config.properties file or Java file, there is a slight but noticeable delay in the UI. The following message appears in the logs:

```
2022-09-06 14:40:59,228 [  79847]   WARN - .diagnostic.PerformanceWatcher - UI was frozen for 5062ms, details saved to /Users/kathrynkodama/devex/editorTooling/open-liberty-tools-intellij/build/idea-sandbox/system/log/threadDumps-freeze-20220906-144059-IC-202.8194.7-Inet6AddressImpl.lookupAllHostAddr-5sec 
Sep. 06, 2022 2:40:59 P.M. org.eclipse.lsp4mp.ls.MicroProfileLanguageServer initialize
INFO: Initializing MicroProfile server 0.5.0-20220725-1527 with /Users/kathrynkodama/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbr-11_0_9-osx-x64-b944.49/jbr/Contents/Home
```

**Comment by turkeylurkey** [comment] 2023-01-31 00:47
Likely caused by line:
https://github.com/OpenLiberty/liberty-tools-intellij/blob/fcbdfff97ae05652424a321509cf37c807d04525/src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/LanguageServerWrapper.java#L694

**Comment by evie-lau** [comment] 2023-04-20 19:48
Seems like none of us really run into this anymore, and I can't seem to reproduce. Closing this issue.

**Closed by evie-lau** 2023-04-20 19:48 UTC
Labels: bug, language client, 3, should-fix
