### ISSUE TITLE
Running dev mode without Liberty plugin defined in build file

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-tools-intellij#43] opened 2021-03-11 16:11 UTC
If a user does not have the Liberty Maven plugin or Liberty Gradle plugin defined in their build file, Open Liberty Tools for IntelliJ could provide an option to start dev mode on the project regardless. 

Alternatively the IntelliJ plugin could add the appropriate plugin to the build file.

**Comment by TrevCraw** [comment] 2023-03-02 20:57
Closed as duplicate of https://github.com/OpenLiberty/liberty-tools-intellij/issues/113

**Closed by TrevCraw** 2023-03-02 20:57 UTC
Labels: duplicate
