### ISSUE TITLE
Errors - "java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only"

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/liberty-tools-intellij#609] opened 2024-01-04 20:56 UTC
Upon opening an existing Maven project (basically this: https://github.com/OpenLiberty/application-stack-intro w/ an updated liberty-maven-plugin) I get this error:

```
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
Current thread: Thread[JobScheduler FJ pool 2/11,4,main] 203513330 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 972430239
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1002)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(WorkspaceFileIndexDataImpl.kt:127)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.getFileInfo(WorkspaceFileIndexDataImpl.kt:70)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getFileInfo(WorkspaceFileIndexImpl.kt:220)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.findFileSetWithCustomData(WorkspaceFileIndexImpl.kt:205)
	at com.intellij.openapi.roots.impl.ModuleFileIndexImpl.isInTestSourceContent(ModuleFileIndexImpl.java:113)
	at io.openliberty.tools.intellij.lsp4mp4ij.psi.internal.core.ls.PsiUtilsLSImpl.getClasspathKind(PsiUtilsLSImpl.java:195)
	at io.openliberty.tools.intellij.lsp4mp4ij.psi.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:86)
	at io.openliberty.tools.intellij.lsp4mp4ij.psi.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:78)
	at io.openliberty.tools.intellij.lsp4mp.lsp.MicroProfileLanguageClient.lambda$getProjectInfo$2(MicroProfileLanguageClient.java:103)
	at org.microshed.lsp4ij.LanguageClientImpl.lambda$runAsBackground$4(LanguageClientImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at org.microshed.lsp4ij.LanguageClientImpl.lambda$runAsBackground$5(LanguageClientImpl.java:115)
	at org.microshed.lsp4ij.LanguageClientImpl.lambda$runAsBackground$6(LanguageClientImpl.java:125)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

As far as I can tell it's just noise.. I haven't noticed anything not working. 

**UPDATE:**  Just noticed it after I created a new file within my project outside the IDE, and the IDE auto-refreshed to pick up the new file.
### ENVIRONMENT
Windows 11
IntelliJ IDEA 2023.1.5 (Community Edition)
Build #IC-231.9392.1, built on July 25, 2023
Runtime version: 17.0.7+10-b829.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Comment by angelozerr** [comment] 2024-01-05 02:48
I suspect this error comes from with your lsp4ij which is out of dated and this error should be fixed by adopting our lsp4ij.

The main idea is to execute serviced in read action mode to avoid this error and to keep good perform1nce get the read action in non blockink context.

Our lsp4ij does that and now all read action problems are diwparead and we have good performance.

**Comment by anusreelakshmi934** [comment] 2024-07-15 08:51
Tested using the Latest Lsp4ij version (0.0.2), was not able to reproduce this error.

**Comment by turkeylurkey** [comment] 2024-07-24 16:07
I opened this project 3 times trying to reproduce this error but it is working correctly now.

**Closed by turkeylurkey** 2024-07-24 16:07 UTC
Labels: bug, language client, lsp4ij
