### ISSUE TITLE
Jakarta EE: Inconsistent behaviour for @Dependent quick fix.

### ISSUE THREAD

**Issue by mrglavas** [OpenLiberty/liberty-tools-intellij#784] opened 2024-05-28 15:53 UTC
While reviewing the Jakarta EE quick fixes, I noticed a difference in behaviour in how the "Replace current scope with `@Dependent`" quick fix is applied when resolving a diagnostic on a field.

Current LT for IntelliJ behaviour:
Applying "Replace current scope with `@Dependent`" to a field adds the annotation to the field.
![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/890521/65b68726-775b-4b1a-95a9-b6cdd3bf1009)
![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/890521/dbc5d530-b309-4f33-b203-d1105eb979e3)

LT for VS Code 24.0.3 behaviour:
Applying "Replace current scope with `@Dependent`" to a field replaces the scope annotation on the class.
![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/890521/7ca64b7a-2e72-4e82-9f0e-c665a5b49bb5)
![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/890521/65df12fb-f611-406d-aaaf-b3e239561b5e)

After applying the quick fix in VS Code it continues to report a diagnostic which cannot be resolved by the quick fix. We should investigate which of these tools (IntelliJ vs. VS Code) has the correct behaviour, assuming either of them are correct.

**Comment by scottkurz** [comment] 2024-05-29 15:01
Seems like the IntelliJ behavior is wrong.   The LT in VSCode and Eclipse both will update the class-level annotation. 

I haven't looked at the whole history or discussion in LSP4Jakarta and am not a CDI expert, but it seems unlikely that the field-level annotation was intended to be updated.    Though the field-level annotation can hold a scope annotation, that's more for things like Producer use cases so not sure it applies here.

I assume the logic of linking the field which has the problem/diagnostic to the class which needs the annotation replaced is somewhere in the `org.eclipse.lsp4jakarta.jdt.internal.cdi;ManagedBeanQuickFix` but I'm not fluent enough to easily make sense of that.   

Anyway hopefully that was a bit of help to mention.

**Comment by mrglavas** [comment] 2024-05-29 15:58
> Seems like the IntelliJ behavior is wrong. The LT in VSCode and Eclipse both will update the class-level annotation.
> 
> I haven't looked at the whole history or discussion in LSP4Jakarta and am not a CDI expert, but it seems unlikely that the field-level annotation was intended to be updated. Though the field-level annotation can hold a scope annotation, that's more for things like Producer use cases so not sure it applies here.
> 
> I assume the logic of linking the field which has the problem/diagnostic to the class which needs the annotation replaced is somewhere in the `org.eclipse.lsp4jakarta.jdt.internal.cdi;ManagedBeanQuickFix` but I'm not fluent enough to easily make sense of that.
> 
> Anyway hopefully that was a bit of help to mention.

@scottkurz Not sure if you caught my observation but updating the class-level annotation does not resolve the diagnostic, so in VSCode when the user applies the quick fix they still get an error. If the quick fix is correct in VSCode then it would seem that the diagnostic is wrong.

**Comment by TrevCraw** [comment] 2024-05-29 19:27
For more context, this is an issue and PR set in LSP4Jakarta where the LT IntelliJ changes were based on: https://github.com/eclipse/lsp4jakarta/issues/444 and https://github.com/eclipse/lsp4jakarta/pull/506

**Comment by scottkurz** [comment] 2024-05-29 20:06
> @scottkurz Not sure if you caught my observation but updating the class-level annotation does not resolve the diagnostic, so in VSCode when the user applies the quick fix they still get an error. If the quick fix is correct in VSCode then it would seem that the diagnostic is wrong. If I manually add @Dependent to the field then VSCode stops reporting the error.

@mrglavas no I didn't notice this before.  I just tried in Eclipse and I see the same thing.  

So, I think it's clear that what should happen is that the class-level annotation gets replaced with `@Dependent`.   As far as what went wrong, well, you and @TrevCraw might know more than me.

I can imagine the opportunity for confusion since we have a field that accepts a certain annotation, but when we look at this field we want to change the annotation elsewhere in the scope (the class).   I'm just recognizing it seems open for possibilities for error but not really claiming to help get us further there.     

Seems likely if both VSCode and Eclipse envs show the same error then something could be wrong in LSP4Jakarta (stating the obvious).

**Comment by dessina-devasia** [comment] 2024-10-22 09:16
Behaviour in IntelliJ, VSCode and Eclipse are attached below:

**Eclipse**
https://github.com/user-attachments/assets/6efb8729-2611-470b-a0a5-d742a90c386b

**VSCode**
https://github.com/user-attachments/assets/f5decdc2-8f3e-4cb0-b866-224314b6dfa6

**IntelliJ**
https://github.com/user-attachments/assets/9a6b7e19-8066-4daa-84fe-0d33d86a24f7

**Comment by TrevCraw** [comment] 2024-10-23 19:46
Hi @dessina-devasia , for the IntelliJ example, what is the diagnostic on the `public int a` field before and after the quick fix adding `@Dependent` is added to the `ManagedBean` class?

**Comment by scottkurz** [comment] 2024-10-24 16:01
Looking at the lsp4jakarta v0.2.1 code in Eclipse, this seems wrong:

This code shouldn't be checking if the field scope is dependent in order to not produce the diagnostic.... it should be looking at the scope of the managed bean itself:

```java
                if (isManagedBean && Flags.isPublic(fieldFlags) && !Flags.isStatic(fieldFlags)
                    && (fieldScopes.size() != 1 || !fieldScopes.get(0).equals(Constants.DEPENDENT_FQ_NAME))) {
                    Range range = PositionUtils.toNameRange(field, context.getUtils());
                    diagnostics.add(context.createDiagnostic(uri,
                                                             Messages.getMessage("ManagedBeanWithNonStaticPublicField"), range,
                                                             Constants.DIAGNOSTIC_SOURCE, null,
                                                             ErrorCode.InvalidManagedBeanWithNonStaticPublicField, DiagnosticSeverity.Error));
                }
```

**Comment by scottkurz** [comment] 2024-10-24 16:04
Re: https://github.com/OpenLiberty/liberty-tools-intellij/issues/784#issuecomment-2435685494   the problem I pointed out seems to be fixed in https://github.com/eclipse/lsp4jakarta/pull/506.    I'm confused, maybe I'm not helping.

**Comment by dessina-devasia** [comment] 2024-10-28 10:32
Hi @TrevCraw,
Here is the video showing the he diagnostic on the` public int a` field before and after the quick fix adding `@Dependent` from `ManagedBean` class

https://github.com/user-attachments/assets/ac6789a5-1182-41d7-915a-abb9747e4152

**Comment by TrevCraw** [comment] 2024-11-05 00:08
Hi @dessina-devasia , after the discussion with @scottkurz and others today, I think these are the next steps:

1. For the scenario that has been outlined in this issue, align the behaviour of LTI with the current behaviour of the LSP4Jakarta main branch (https://github.com/eclipse/lsp4jakarta). The current behaviour for this scenario was added by this PR: https://github.com/eclipse/lsp4jakarta/pull/506.
2. @turkeylurkey is going to look into the behaviour introduced to LSP4Jakarta by this section of the PR -  https://github.com/eclipse/lsp4jakarta/pull/506/files#diff-499e942372a6d850d8e4aee1ef38dc77d7b1d4ac33c0ff51b54bb49af5f1af59R100-R111 - to determine if this behaviour is correct or not.

**Comment by turkeylurkey** [comment] 2024-11-05 04:21
Testing on the latest code compiled in Eclipse I found that the quick fix resolved both diagnostics in the test case shown above (which is not the latest in the test suite). The bug in IntelliJ is that the quick fix is applied to the field whereas the fix should be applied to the class even when you use the quick fix from the field.

**Comment by turkeylurkey** [comment] 2024-11-08 20:20
The latest test for the diagnostic is now available in LSP4Jakarta. Please convert this test and use it in the appropriate diagnostic collector in IntelliJ. The other piece of work for this issue is to update the quick fix so that if the quick fix on the field is selected then it updates the annotation on the class rather than on the field.

https://github.com/eclipse/lsp4jakarta/blob/10887f94c2d29624452f8ad6f76608259af9fb8d/jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/internal/cdi/ManagedBeanDiagnosticsParticipant.java#L89

More info: https://github.com/eclipse/lsp4jakarta/issues/534

**Comment by TrevCraw** [comment] 2024-11-08 20:28
Hi @dessina-devasia , please align the behaviour in LTI with the behaviour @turkeylurkey has added to LSP4Jakarta.

**Comment by dessina-devasia** [comment] 2024-11-11 06:58
Sure @TrevCraw

**Closed** 2024-11-13 14:33 UTC
Labels: language client, medium priority, design, parity
