### ISSUE TITLE
Slow LSP responses breaking features on Windows

### ISSUE THREAD

**Issue by Jonathan-Maciel** [OpenLiberty/liberty-tools-intellij#689] opened 2024-03-13 16:37 UTC
Liberty Tools Driver: 24.0.3-SNAPSHOT
Windows 11 VM with 16GB RAM
IntelliJ IDEA 2023.3.4 (Community Edition)
OpenJDK 18.0.2

Hovering a feature does not display the documentation: 
![Screenshot 2024-03-12 at 11 17 56 AM](https://github.com/OpenLiberty/liberty-tools-vscode/assets/104153033/6131da08-b019-46fd-8fb9-b809555189a4)

The response time is consistently over 2.5 seconds:
<img width="1635" alt="Screenshot 2024-03-12 at 1 14 18 PM" src="https://github.com/OpenLiberty/liberty-tools-vscode/assets/104153033/6aa34af6-537a-4f35-9038-d962aadc0183">

The feature completion also takes over 10 seconds:
![Screenshot 2024-03-12 at 1 24 22 PM](https://github.com/OpenLiberty/liberty-tools-vscode/assets/104153033/202453c1-64b4-45c2-ba0e-072c5e3ffb64)

**Comment by TrevCraw** [comment] 2024-03-26 15:41
Closing as duplicate of https://github.com/OpenLiberty/liberty-tools-intellij/issues/689. We will track updates and progress in that issue instead.

**Closed by TrevCraw** 2024-03-26 15:41 UTC
Labels: bug, duplicate, SVT, performance
