### ISSUE TITLE
Diagnostics not appearing when files are closed and reopened (all language servers)

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-intellij#367] opened 2023-04-21 22:41 UTC
This was originally documented in https://github.com/OpenLiberty/liberty-tools-intellij/issues/329 since it was thought it was related. The fix for https://github.com/OpenLiberty/liberty-tools-intellij/issues/329 (PR https://github.com/OpenLiberty/liberty-tools-intellij/pull/355) does not seem to resolve this issue.

Existing behaviour:
If there are issues that result in diagnostics in server.env or bootstrap.properties, the diagnostics do not appear when the file is opened.

For example, create a diagnostic in server.env
![image](https://user-images.githubusercontent.com/5885743/232157670-818d56c6-52c4-4609-b335-de0906d86e52.png)
Close, and reopen server.env - The diagnostic underline shows up right as the file is opened, but disappears immediately. You can see that there is still a red exclamation mark in the top corner of the file, but it does not show up in the "Problems" view.
![image](https://user-images.githubusercontent.com/5885743/232158012-e67ac17c-7627-46ad-8b0a-f56b59deb939.png)
The red exclamation mark eventually disappears as well.
![image](https://user-images.githubusercontent.com/5885743/232158157-816a3473-6e1a-45e8-8bbc-40ae097d4470.png)
Hovering does not trigger the diagnostic to show up (edit: intermittently, hover actually can trigger the diagnostic to show up)
![image](https://user-images.githubusercontent.com/5885743/232158327-bce92a43-987e-4732-9db9-d5f0a4d6d95f.png)
Only input into the file (ie. type enter for new line) triggers the diagnostic to show up again
![image](https://user-images.githubusercontent.com/5885743/232158443-7d98b1bf-4658-4a89-926f-3e706ed0fb54.png)

**Comment by evie-lau** [comment] 2023-04-24 16:54
Interesting.. it seems I can only reproduce this if closing and _reopening the file for the second time_ in a session.
But the very first time opening the file in an IDE session will have diagnostics show up in the editor and problems view. This is happening in **all the language servers**.

**Comment by evie-lau** [comment] 2023-04-25 21:44
The diagnostic rewrite from intellij-quarkus seems to fix this issue regarding diagnostics when closing/reopening files, but brings back the previous issue of not showing diagnostics on startup/first time opening a file. I patched it with code similar to our original implementation which solves the startup issue.

However the diagnostic rewrite has some alarming Exceptions (but classified as warnings) due to some deprecated methods used - will be monitoring intellij-quarkus for updates on using non-deprecated APIs.

**Comment by angelozerr** [comment] 2023-04-27 23:16
> The diagnostic rewrite from intellij-quarkus seems to fix this issue regarding diagnostics when closing/reopening files, but brings back the previous issue of not showing diagnostics on startup/first time opening a file. I patched it with code similar to our original implementation which solves the startup issue.

Have you again the issue with the last PR that I did and that we have merged in intellij-quarkus? 

> However the diagnostic rewrite has some alarming Exceptions (but classified as warnings) due to some deprecated methods used - will be monitoring intellij-quarkus for updates on using non-deprecated APIs.

Indeed, I don't thake care of this issue, please see https://github.com/redhat-developer/intellij-quarkus/pull/827

**Comment by angelozerr** [comment] 2023-04-28 08:07
@evie-lau in my case diagnostics appears every time (even the first time when language server is not started), please give me feedback to know if my support ofLSP diagnostics works in your case.

**Comment by angelozerr** [comment] 2023-04-28 14:41
What about with LemMinx XML language server?

**Comment by evie-lau** [comment] 2023-04-28 14:51
I know our Liberty LemMinx plugin does not show diagnostics on startup. 
I'm not too familiar with what diagnostics come from LemMinx vs IntelliJ on an XML file - would you be able to provide a test case for me?

**Comment by angelozerr** [comment] 2023-04-28 14:53
> I'm not too familiar with what diagnostics come from LemMinx vs IntelliJ on an XML file - would you be able to provide a test case/string for me?

Sorry I will not have time to do that, I wanted just to know if you had some trouble with lemMinx which is working great in Eclipse IDE and vscode. Never tested in IJ.

**Comment by angelozerr** [comment] 2023-04-28 14:58
And what about your Jakarta LS?

**Comment by angelozerr** [comment] 2023-04-28 16:32
Could you please give me a project that you are using and which file you open which causes the issue.

**Comment by evie-lau** [comment] 2023-04-28 16:36
@angelozerr I contacted you at [gitter.im](https://gitter.im/). Hopefully it will be easier to discuss there

**Comment by angelozerr** [comment] 2023-04-29 07:06
> @angelozerr I contacted you at [gitter.im](https://gitter.im/). Hopefully it will be easier to discuss there

Thanks.

For your problem with diagnostics which doesn't apper when the language server starts, I suspect it is because you don't force this start when file is opened.

It seems that you never used [ConnectDocumentToLanguageServerSetupParticipant ](https://github.com/OpenLiberty/liberty-tools-intellij/blob/main/src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/ConnectDocumentToLanguageServerSetupParticipant.java) which takes care of this start when file is opened https://github.com/OpenLiberty/liberty-tools-intellij/blob/741843c0352830a903dba8ff97764d26f4702933/src/main/java/io/openliberty/tools/intellij/lsp4mp/lsp4ij/ConnectDocumentToLanguageServerSetupParticipant.java#L45 

You need to register this component in the lsp.xml like we did

https://github.com/redhat-developer/intellij-quarkus/blob/35a8a4126c6ff21227c8ec606658c62e8fd11e65/src/main/resources/META-INF/lsp.xml#L57

**Comment by angelozerr** [comment] 2023-04-29 12:26
@evie-lau for discussion I suggest we use https://gitter.im/eclipse/microprofile-languageserver

**Comment by evie-lau** [comment] 2023-05-01 14:33
> You need to register this component in the lsp.xml like we did

Thank you, that fixed it. Along with the diagnostic rewrite, this issue and #329 will be fully resolved.

**Closed** 2023-05-03 15:59 UTC
Labels: bug, language client, must-fix
