### ISSUE TITLE
Intelij: 2024.2 Update Test Automation in Mac

### ISSUE THREAD

**Issue by vaisakhkannan** [OpenLiberty/liberty-tools-intellij#1066] opened 2024-11-01 06:22 UTC
Update UI test automation on Mac to support IntelliJ 2024.2.

- [x] SingleModJakartaLSTestCommon 
- [x] SingleModLibertyLSTestCommon 
- [x] SingleModMPLSTestCommon
- [x] SingleModMPProjectTestCommon 
- [x] SingleModNLTRestProjectTestCommon
- [x] Getting NullPointerException while running individual UI tests in local environment

**Comment by staicy123** [comment] 2024-11-05 11:49
- [ ] testOpenBuildFileActionUsingPopUpMenu
- [ ] testStartWithParamsActionUsingDropDownMenu
- [ ] testStartWithParamsActionUsingPlayToolbarButton
- [ ] testStartWithParamsActionUsingPopUpMenu
- [ ] testStartWithParamsActionUsingSearch
- [ ] testRunTestsActionUsingDropDownMenu
- [ ] testRunTestsActionUsingPlayToolbarButton
- [ ] testRunTestsActionUsingPopUpMenu
- [ ] testRunTestsActionUsingSearch
- [ ] testStartWithConfigInDebugModeUsingToolbar
- [ ] testStartWithConfigInDebugModeUsingMenu
- [ ] testStartWithConfigInRunModeUsingToolbar
- [ ] testStartWithConfigInRunModeUsingMenu
- [ ] testMultipleConfigEditHistory
- [ ] testStartInContainerActionUsingDropDownMenu
- [ ] testStartInContainerActionUsingPlayToolbarButton
- [ ] testStartInContainerActionUsingPopUpMenu
- [ ] testStartInContainerActionUsingSearch
- [ ] prepareEnv
- [ ] testCustomStartParametersClearedOnConfigRemoval

**Comment by staicy123** [comment] 2024-11-14 10:17
SingleModLibertyLSTestCommon

 prepareEnv & cleanup
 testServerXMLFeatureHover
 testServerXMLNonFeatureHover
 testInsertFeatureIntoServerXML
 testInsertLibertyConfigElementIntoServerXML
 testInsertLibertyConfigIntoServerEnv
 testInsertLibertyConfigIntoBootstrapProps
 testServerEnvCfgHover
 testBootstrapPropsCfgHover
 testDiagnosticInServerXML
 testQuickFixInServerXML
 testDiagnosticInServerEnv
 testDiagnosticInBootstrapProperties

**Comment by staicy123** [comment] 2024-11-14 10:47
**SingleModJakartaLSTestCommon**

- [ ]  testInsertJakartaCodeSnippetIntoJavaPart
- [ ]  testJakartaDiagnosticsInJavaPart
- [ ]  testJakartaQuickFixInJavaPart

**Comment by staicy123** [comment] 2024-11-14 10:51
**SingleModMPLSTestCommon**

 

- [ ] testInsertCodeSnippetIntoJavaPart
- [ ]  testMPDiagnosticsInJavaPart
- [ ]  testMPQuickFixInJavaFile
- [ ]  testInsertMicroProfileProperty
- [ ]  testMicroProfileConfigHover
- [ ]  testDiagnosticInMicroProfileConfigProperties
- [ ]  testQuickFixInMicroProfileConfigProperties

**Comment by staicy123** [comment] 2024-11-19 11:31
Hi @TrevCraw,
All UI tests that ran locally on Mac were successful. However, when the tests were executed in GHA, a few failures were encountered. Based on the last AHA build run, a total of 118 tests were executed, with 29 failing. Of these, 16 are unit test failures and 1 is a known UI test failure. Additionally, I observed a SocketTimeoutException, which is a known issue. I expect this to be resolved once the fix for this issue is pulled into our branch. I am currently working on fixing the test failures found in the GHA build, addressing each issue one by one. The main issues I found are due to the text either not existing or not being rendered in time. As a solution, I am adding some delay or wait time to allow for proper rendering before attempting to find the text.
<img width="1713" alt="Screenshot 2024-11-19 at 4 52 43 PM" src="https://github.com/user-attachments/assets/8914c6af-ceff-458f-a8a8-f83bc45602ec">


Thanks

**Comment by staicy123** [comment] 2024-11-21 12:32
Hi @TrevCraw,
I’d like to bring to your attention the issues I mentioned in my earlier comment. While I was able to run all the tests locally without any failures, the same tests are failing in GHA. A total of 120 tests were executed, with 31 failing. Among these, 13 tests failed due to my changes, 16 failed due to unit test issues, and 1 UI test failure is a known issue.
The primary failures are occurring in the code responsible for locating and interacting with new menu items. Upon analysis, I observed that the same functionality is being called across multiple files. While it works in the majority of cases, it fails for certain tests. For example, in tests using different projects, the functionality succeeds in three instances but fails in one.
After reviewing the failure videos, I noticed that the failed tests are unable to locate the elements at the correct time. To address this, I tried several approaches:
Adding delays using the TestUtils.sleepAndIgnoreException method after each click (didn’t work).
Using the RepeatUtilsKt.waitFor() method to introduce delays (also didn’t work).
Adding indexing waits, as some failure videos showed indexing occurring before the menu click (this approach didn’t work either).
Additionally, I noticed a delay in Mac UI click functionality compared to Windows and Linux. In some cases, the menu item windows are not displayed properly and appear blurred. When I checked the cron jobs running against the main branch, I found similar failures due to delays in Mac UI.
I’ve attached links to the failure videos from my tests as well as those from the main branch’s cron jobs for reference.
**Main branch UI video:**

https://github.com/user-attachments/assets/562cc8fb-8a52-49af-9dfc-3e55b8fffff6

https://github.com/user-attachments/assets/0bc7521d-8dc4-4922-a792-13f9864750fa


**Intellij 2024.2 UI changes for Mac:**


At this point, I’ve exhausted all the solutions I could think of. If you have any suggestions or ideas, I’d greatly appreciate your input.
Also, I’d like to remind you of the workaround I used earlier during the initial stages of UI fixes, where direct menu item clicks weren’t working. The workaround involved performing all menu actions using the "Search Everywhere" icon in IntelliJ, which worked successfully in my local setup. If you think this approach could work as a temporary solution, I can make the necessary changes and test if the GHA builds pass with it.
Looking forward to your feedback!

**Comment by staicy123** [comment] 2024-11-27 13:32
Hi @TrevCraw,

I wanted to update you on the progress. By implementing the workaround using the Search Everywhere feature instead of directly clicking on menu items, I was able to successfully run the tests.

Here’s the link to the test run: [GitHub Actions Run](https://github.com/staicy123/liberty-tools-intellij/actions/runs/12024089318/job/33525671807).

Currently, the issue arises when attempting to run 10 builds simultaneously. Most of the builds fail due to SocketTimeoutException and initialization errors. I believe these issues will likely be resolved once Paul raises the PR for the fix he is working on, and I can incorporate his changes.

For now, I plan to raise a draft PR with my changes https://github.com/OpenLiberty/liberty-tools-intellij/pull/1136. Once Paul’s fixes are merged, I will test everything together and update the PR accordingly before final submission.

Thanks,

**Comment by staicy123** [comment] 2024-12-04 13:19
I have been working on this issue testing the UI changes by integrating all the latest updates merged into the 2024.2-intellij-backup branch. While I was able to achieve successful builds, I noticed intermittent failures caused by a java.lang.OutOfMemoryError: Java heap space.
 https://github.com/staicy123/liberty-tools-intellij/actions/runs/12153694930/job/33892200493
https://github.com/staicy123/liberty-tools-intellij/actions/runs/12153919353/job/33892809988
https://github.com/staicy123/liberty-tools-intellij/actions/runs/12153694930/job/33892200722
@turkeylurkey , any suggestion on this issue?

Thanks

**Comment by turkeylurkey** [comment] 2024-12-04 22:18
@staicy123  I have seen this problem before when I was working with the old JDK 17.0.6. I thought the new one (17.0.13) had fixed it. 

Since you find the option you specified resolves it I agree that you should add it to your branch with the following caveats. Could you experiment with 2g and 4g? Also, could you add Linux and Windows back into your builds because we need to test this option with all the platforms.

**Comment by staicy123** [comment] 2024-12-05 11:11
Hi @turkeylurkey,
As suggested I tried with 2g instead of 4g and could see its working in all OS and I have also added this change as part of my UI changes PR.
https://github.com/staicy123/liberty-tools-intellij/actions/runs/12174089393
Thanks,

**Closed** 2024-12-06 10:01 UTC
Labels: enhancement, high priority, 5
