### ISSUE TITLE
Missing descriptions on hover for elements and features in server.xml (Windows)

### ISSUE THREAD

**Issue by dessina-devasia** [OpenLiberty/liberty-tools-intellij#694] opened 2024-03-19 15:19 UTC
During the FVT testing of liberty-tools version 24.0.3-SNAPSHOT on a Windows 11 environment, I encountered an issue where the documentation for any elements or feature descriptions within the server.xml file could not be found. 

For reference, I've attached a screenshot below showcasing the absence of documentation within the server.xml file.

![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/143582034/ddeff72b-a648-4103-88c2-89972c7f7318)

![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/143582034/dc0bbef7-8590-4d8c-9890-938cb76dc888)

**Comment by mrglavas** [comment] 2024-03-19 18:02
I think this may have been exposed by the performance issue we're investigating with LCLS: https://github.com/OpenLiberty/liberty-tools-intellij/issues/687, but seems the root cause might be in LSP4iJ. I think I found where `textDocument/hover` is supported: https://github.com/MicroShed/lsp4ij/blob/main/src/main/java/org/microshed/lsp4ij/operations/documentation/LSPTextHoverForFile.java and can see there's a short time-out. I wonder if this could be improved similarly to what was recently done for quick fixes where it actually waits for the response and will work even if the server is slow.

**Comment by angelozerr** [comment] 2024-03-19 21:00
I improved in our lsp4ij the hover and now it should work without timeout.

Since your last update I did a lot of refactoring break some api etc.

I suggest you really to be based on our lsp4ij

**Comment by TrevCraw** [comment] 2024-03-22 16:21
PR here should mitigate this issue until we are able to move to a newer version of lsp4ij: https://github.com/MicroShed/lsp4ij/pull/14

**Comment by TrevCraw** [comment] 2024-05-06 20:00
Review if LSP4IJ updates from April 1st contain the complete fix for this problem. Test the behaviour to verify the fix.

**Comment by mrglavas** [comment] 2024-05-10 16:52
I've confirmed that this issue has been resolved by the upgrade to LSP4iJ 2024/04/01. Hover now displays "Fetching Documentation..." while waiting for the response and then displays the documentation for the feature once the response has been returned and processed. The class `LSPTextHoverForFile.java` which had been patched to mitigate this issue no longer exists.

![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/890521/d89d6163-2d41-4f8a-9492-95f044918db4)
![image](https://github.com/OpenLiberty/liberty-tools-intellij/assets/890521/7ea767e9-93fa-4611-a35d-d849bc46c179)

**Closed by mrglavas** 2024-05-10 16:52 UTC
Labels: bug, should-fix
