### ISSUE TITLE
Filtering for completion in server.env and bootstrap.properties is case sensitive

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-intellij#897] opened 2024-08-02 19:26 UTC
Need to investigate if this is a regression or not. Verified this is present in LT IntelliJ 24.0.6. Should also check to see if this bug is present with LT VS Code.

There may be other files affected as well, need to investigate (i.e. server.xml, Java files, etc).

![image](https://github.com/user-attachments/assets/597e9059-b1b7-4efd-ba6f-9f67ea79d762)

![image](https://github.com/user-attachments/assets/ead7b227-2428-4578-9af1-2349ec919290)

***As part of this issue, the UI LS tests should be expanded to cover this scenario.

**Comment by turkeylurkey** [comment] 2024-08-02 20:47
Tried this in VS Code which uses 24.0.3 and upper and lower case are treated the same
<img width="331" alt="image" src="https://github.com/user-attachments/assets/5b58d707-a70c-4d77-a387-bc9dd70bd03c">

**Comment by vaisakhkannan** [comment] 2024-08-19 09:44
I tried this in VS Code, which uses versions `24.0.3` and` 23.0.12`. In all cases—whether in server.env, bootstrap.properties, Java files, or server.xml files—`upper and lower case are treated the same`.

**Comment by vaisakhkannan** [comment] 2024-08-20 08:52
I found that in `IntelliJ Settings`, under `Editor → General → Code Completion`, unchecking the `Match case` checkbox allows the suggestions to appear properly without being case-sensitive for `server.env` and `bootstrap.properties` files.
By default, IntelliJ has the _**checkbox enabled**_, which is why we are not getting suggestions for the respective cases in the server.env and bootstrap.properties files. When I checked in VS Code, it currently does not have a feature to enable or disable case-sensitive code-completion, which I believe is the reason we always get suggestions in both server.env and bootstrap.properties files in vscode

**Comment by vaisakhkannan** [comment] 2024-08-20 12:35
I found a way to disable the 'Match case' option in IntelliJ through our plugin code. However, the issue is that this will completely disable the 'Match case' checkbox for completions once our plugin is installed:

<img width="892" alt="Screenshot 2024-08-20 at 6 04 17 PM" src="https://github.com/user-attachments/assets/6e4d7624-f797-4b49-b62f-44c87e60f596">

```
CodeInsightSettings settings = CodeInsightSettings.getInstance();
settings.COMPLETION_CASE_SENSITIVE = CodeInsightSettings.NONE;
```

**Comment by angelozerr** [comment] 2024-09-05 13:14
This problem comes from LSP4IJ, I created a PR (with test) at https://github.com/redhat-developer/lsp4ij/pull/511

I will integrate this fix in the 0.5.0 version.

**Comment by angelozerr** [comment] 2024-09-05 15:40
Please try https://github.com/redhat-developer/lsp4ij?tab=readme-ov-file#testing-nightly-builds it should fix your issue.

**Comment by mrglavas** [comment] 2024-09-06 18:18
@angelozerr I had already pulled the recent source from LSP4iJ and built locally. I can confirm that case insensitive filtering is now working for `server.env` and `bootstrap.properties`. Thanks for addressing this issue.

**Comment by vaisakhkannan** [comment] 2024-09-09 04:43
I can also confirm that the case sensitivity issue mentioned is no longer occurring for the completion in `bootstrap.properties` and `server.env` files.

**Closed** 2024-09-24 03:44 UTC
Labels: documentation, should-fix
